version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "test"
    ports:
      - "5433:5432"
    network_mode: "host"
    restart: always
      
  user-management:
    build: https://github.com/RenanMouraDaSilvaBarros/user-management.git
    ports:
      - "3000:3000"
    network_mode: "host"
    depends_on:
      - postgres


